spring:
  application:
    name: credential-issuer-backend

server:
  port: 8080

oid4vci:
  credential-issuer: "https://issuer-dev.in2.ssihub.org"
  authorization-server: "https://issuer-dev.in2.ssihub.org"
